import { ToolMetadata } from "./types";

export const toolsRegistry: ToolMetadata[] = [
  // ==================== PDF TOOLS ====================
  {
    name: "PDF to JPG",
    slug: "pdf-to-jpg",
    category: "pdf",
    description: "Turn your PDF pages into simple JPG photos in seconds.",
    iconName: "FileImage",
    color: "cyan",
    creditsCost: 5,
    acceptedFileTypes: [".pdf"],
    outputFileTypes: [".jpg"],
    maxFileSizeBytes: 25 * 1024 * 1024, // 25MB
    seoTitle: "Convert PDF to JPG Online - Turn PDF Pages to Images",
    seoDescription: "Easily turn PDF pages into JPG images. Simple, safe, and fast.",
    schemaType: "SoftwareApplication",
    settings: [
      {
        name: "quality",
        label: "Photo Quality",
        type: "slider",
        defaultValue: 90,
        min: 10,
        max: 100,
        step: 5,
      },
    ],
  },
  {
    name: "JPG to PDF",
    slug: "jpg-to-pdf",
    category: "pdf",
    description: "Combine your JPG and JPEG pictures into a clean PDF document.",
    iconName: "FileCode",
    color: "cyan",
    creditsCost: 5,
    acceptedFileTypes: [".jpg", ".jpeg"],
    outputFileTypes: [".pdf"],
    maxFileSizeBytes: 15 * 1024 * 1024, // 15MB
    seoTitle: "Convert JPG to PDF Online - Combine Images to PDF",
    seoDescription: "Convert your pictures into a single PDF document. Choose page alignment and orientation.",
    schemaType: "SoftwareApplication",
    settings: [
      {
        name: "orientation",
        label: "Page Layout",
        type: "select",
        defaultValue: "portrait",
        options: ["portrait", "landscape"],
      },
      {
        name: "margin",
        label: "Add Margins",
        type: "toggle",
        defaultValue: false,
      },
    ],
  },
  {
    name: "Merge PDF",
    slug: "pdf-merge",
    category: "pdf",
    description: "Combine multiple PDF files into one single document.",
    iconName: "FolderPlus",
    color: "cyan",
    creditsCost: 5,
    acceptedFileTypes: [".pdf"],
    outputFileTypes: [".pdf"],
    maxFileSizeBytes: 50 * 1024 * 1024, // 50MB combined
    seoTitle: "Merge PDF Files Online - Combine PDFs",
    seoDescription: "Combine multiple PDF files into one. Simply drag and drop, set the order, and merge.",
    schemaType: "SoftwareApplication",
    settings: [],
  },
  {
    name: "Split PDF",
    slug: "pdf-split",
    category: "pdf",
    description: "Take out specific pages from a PDF or split them into separate files.",
    iconName: "Scissors",
    color: "cyan",
    creditsCost: 5,
    acceptedFileTypes: [".pdf"],
    outputFileTypes: [".pdf"],
    maxFileSizeBytes: 30 * 1024 * 1024,
    seoTitle: "Split PDF Online - Extract Pages from PDF",
    seoDescription: "Split PDF pages easily. Specify the page numbers you want to extract.",
    schemaType: "SoftwareApplication",
    settings: [
      {
        name: "splitRange",
        label: "Pages to Extract (e.g. 1-3, 5)",
        type: "text",
        defaultValue: "all",
      },
    ],
  },
  {
    name: "Compress PDF",
    slug: "pdf-compress",
    category: "pdf",
    description: "Make your PDF file smaller so it is easy to send, without losing quality.",
    iconName: "FileDown",
    color: "cyan",
    creditsCost: 5,
    acceptedFileTypes: [".pdf"],
    outputFileTypes: [".pdf"],
    maxFileSizeBytes: 40 * 1024 * 1024,
    seoTitle: "Compress PDF Online - Make PDF File Size Smaller",
    seoDescription: "Optimize and shrink your PDF document size for easy email sharing and fast loading.",
    schemaType: "SoftwareApplication",
    settings: [
      {
        name: "compressionLevel",
        label: "How small?",
        type: "select",
        defaultValue: "recommended",
        options: ["low (best quality)", "recommended", "high (smallest file)"],
      },
    ],
  },
  {
    name: "PDF to Word",
    slug: "pdf-to-word",
    category: "pdf",
    description: "Turn your PDF files into editable Word documents that you can change.",
    iconName: "FileText",
    color: "cyan",
    creditsCost: 8,
    acceptedFileTypes: [".pdf"],
    outputFileTypes: [".docx"],
    maxFileSizeBytes: 20 * 1024 * 1024,
    seoTitle: "Convert PDF to Word Online - Free PDF to Word",
    seoDescription: "Turn PDF files into editable Word documents. Text alignment and structures are preserved.",
    schemaType: "SoftwareApplication",
    settings: [],
  },
  {
    name: "Word to PDF",
    slug: "word-to-pdf",
    category: "pdf",
    description: "Turn Word documents into clean PDFs.",
    iconName: "FileUp",
    color: "cyan",
    creditsCost: 5,
    acceptedFileTypes: [".docx", ".doc"],
    outputFileTypes: [".pdf"],
    maxFileSizeBytes: 15 * 1024 * 1024,
    seoTitle: "Convert Word DOCX to PDF Online",
    seoDescription: "Convert Word files (DOC and DOCX) to PDF with exact layout retention.",
    schemaType: "SoftwareApplication",
    settings: [],
  },
  {
    name: "Excel to PDF",
    slug: "excel-to-pdf",
    category: "pdf",
    description: "Turn your Excel sheets into printable PDF files.",
    iconName: "Grid",
    color: "cyan",
    creditsCost: 5,
    acceptedFileTypes: [".xlsx", ".xls"],
    outputFileTypes: [".pdf"],
    maxFileSizeBytes: 15 * 1024 * 1024,
    seoTitle: "Convert Excel to PDF Online - Sheets to PDF",
    seoDescription: "Convert Excel spreadsheets to PDF format. Automatically fits sheets and columns to page formats.",
    schemaType: "SoftwareApplication",
    settings: [
      {
        name: "fitToPage",
        label: "Fit to page width",
        type: "toggle",
        defaultValue: true,
      },
    ],
  },
  {
    name: "PPT to PDF",
    slug: "ppt-to-pdf",
    category: "pdf",
    description: "Turn your PowerPoint slides into a PDF file.",
    iconName: "Presentation",
    color: "cyan",
    creditsCost: 5,
    acceptedFileTypes: [".pptx", ".ppt"],
    outputFileTypes: [".pdf"],
    maxFileSizeBytes: 25 * 1024 * 1024,
    seoTitle: "Convert PPT slides to PDF Online - PowerPoint to PDF",
    seoDescription: "Transform PowerPoint presentation slides into a PDF document in one click.",
    schemaType: "SoftwareApplication",
    settings: [],
  },

  // ==================== IMAGE TOOLS ====================
  {
    name: "Image Compressor",
    slug: "image-compress",
    category: "image",
    description: "Make your images smaller and easier to share without losing quality.",
    iconName: "ChevronsDownUp",
    color: "pink",
    creditsCost: 2,
    acceptedFileTypes: [".png", ".jpg", ".jpeg", ".webp"],
    outputFileTypes: [".png", ".jpg", ".webp"],
    maxFileSizeBytes: 15 * 1024 * 1024,
    seoTitle: "Compress Images Online - Reduce Picture Size Free",
    seoDescription: "Compress PNG, JPG, and WebP images. Make file sizes smaller for easy sending.",
    schemaType: "SoftwareApplication",
    settings: [
      {
        name: "quality",
        label: "Quality",
        type: "slider",
        defaultValue: 80,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    name: "Background Remover",
    slug: "bg-remover",
    category: "image",
    description: "Remove backgrounds from your photos instantly.",
    iconName: "Sparkles",
    color: "pink",
    creditsCost: 15,
    acceptedFileTypes: [".png", ".jpg", ".jpeg", ".webp"],
    outputFileTypes: [".png"],
    maxFileSizeBytes: 10 * 1024 * 1024,
    seoTitle: "Remove Image Background Online - Transparent Background",
    seoDescription: "Instantly remove image backgrounds. Clean edge extraction creates transparent PNGs.",
    schemaType: "SoftwareApplication",
    settings: [],
  },
  {
    name: "Image Resizer",
    slug: "image-resize",
    category: "image",
    description: "Change the size and width of your pictures.",
    iconName: "Maximize2",
    color: "pink",
    creditsCost: 3,
    acceptedFileTypes: [".png", ".jpg", ".jpeg", ".webp"],
    outputFileTypes: [".png", ".jpg", ".webp"],
    maxFileSizeBytes: 12 * 1024 * 1024,
    seoTitle: "Resize Images Online - Change Image Size",
    seoDescription: "Resize PNG, JPG, and WebP dimensions to exact pixel widths and heights.",
    schemaType: "SoftwareApplication",
    settings: [
      {
        name: "width",
        label: "Width (pixels)",
        type: "number",
        defaultValue: 1024,
      },
      {
        name: "height",
        label: "Height (pixels)",
        type: "number",
        defaultValue: 768,
      },
      {
        name: "maintainAspectRatio",
        label: "Lock proportions",
        type: "toggle",
        defaultValue: true,
      },
    ],
  },
  {
    name: "Image Cropper",
    slug: "image-crop",
    category: "image",
    description: "Cut out the edges of your pictures to fit social media shapes.",
    iconName: "Crop",
    color: "pink",
    creditsCost: 3,
    acceptedFileTypes: [".png", ".jpg", ".jpeg", ".webp"],
    outputFileTypes: [".png", ".jpg", ".webp"],
    maxFileSizeBytes: 12 * 1024 * 1024,
    seoTitle: "Crop Images Online - Cut Picture Edges Free",
    seoDescription: "Crop image files easily. Trim boundaries, customize framing boxes, or set pre-defined ratios.",
    schemaType: "SoftwareApplication",
    settings: [
      {
        name: "aspectRatio",
        label: "Aspect Ratio",
        type: "select",
        defaultValue: "free",
        options: ["free", "1:1 square", "16:9 cinematic", "4:3 standard", "9:16 mobile"],
      },
    ],
  },
  {
    name: "WebP Converter",
    slug: "webp-convert",
    category: "image",
    description: "Convert your JPG or PNG pictures into fast-loading WebP files.",
    iconName: "ImagePlay",
    color: "pink",
    creditsCost: 3,
    acceptedFileTypes: [".png", ".jpg", ".jpeg"],
    outputFileTypes: [".webp"],
    maxFileSizeBytes: 15 * 1024 * 1024,
    seoTitle: "Convert Images to WebP Online",
    seoDescription: "Convert images to WebP online. Speed up web pages with high-performance WebP assets.",
    schemaType: "SoftwareApplication",
    settings: [
      {
        name: "quality",
        label: "Compression Quality",
        type: "slider",
        defaultValue: 75,
        min: 10,
        max: 100,
        step: 5,
      },
    ],
  },
  {
    name: "PNG to JPG",
    slug: "png-to-jpg",
    category: "image",
    description: "Change your PNG files into standard JPG images.",
    iconName: "RefreshCw",
    color: "pink",
    creditsCost: 2,
    acceptedFileTypes: [".png"],
    outputFileTypes: [".jpg"],
    maxFileSizeBytes: 10 * 1024 * 1024,
    seoTitle: "Convert PNG to JPG Online - Instant Conversion",
    seoDescription: "Easily convert PNG files into standard JPG images online. Secure, fast, and completely free.",
    schemaType: "SoftwareApplication",
    settings: [],
  },
  {
    name: "JPG to PNG",
    slug: "jpg-to-png",
    category: "image",
    description: "Change your JPG images into high-quality PNG files.",
    iconName: "RefreshCcw",
    color: "pink",
    creditsCost: 2,
    acceptedFileTypes: [".jpg", ".jpeg"],
    outputFileTypes: [".png"],
    maxFileSizeBytes: 10 * 1024 * 1024,
    seoTitle: "Convert JPG to PNG Online",
    seoDescription: "Convert JPG and JPEG files to PNG format. Keep premium graphic output fidelity online.",
    schemaType: "SoftwareApplication",
    settings: [],
  },
];

export function getToolBySlug(slug: string): ToolMetadata | undefined {
  return toolsRegistry.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: "pdf" | "image"): ToolMetadata[] {
  return toolsRegistry.filter((t) => t.category === category);
}
